language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov

script:
  - pytest --cov=ecs_task_run --cov-report=xml

after_success:
  - codecov
